----- 회원정보

CREATE TABLE "MEMBER" (
	"ID" VARCHAR2(20) NOT NULL ENABLE, -- 회원아이디
	"NAME" VARCHAR2(20) NOT NULL ENABLE, -- 회원이름
	"PASS" VARCHAR2(20) NOT NULL ENABLE, -- 비밀번호
	"PHONE1" VARCHAR2(5) NOT NULL ENABLE, -- 폰번호1
	"PHONE2" VARCHAR2(5) NOT NULL ENABLE, -- 폰번호2
	"PHONE3" VARCHAR2(5) NOT NULL ENABLE, -- 폰번호3
	"EMAIL" VARCHAR2(50) NOT NULL ENABLE, -- 이메일주소
	"BIRTH1" NUMBER(4,0) NOT NULL ENABLE, -- 생년
	"BIRTH2" NUMBER(2,0) NOT NULL ENABLE, -- 생월
	"BIRTH3" NUMBER(2,0) NOT NULL ENABLE, -- 생일
	"F_SINGER" VARCHAR2(500), -- 좋아하는가수 (콤마[,]로 구분)
	"F_GENRE" VARCHAR2(500), -- 좋아하는장르 (콤마[,]로 구분)
	"POINT" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE, -- 회원보유포인트
	"REGDATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, -- 회원가입일자
	CONSTRAINT "MEMBER_PK" PRIMARY KEY ("ID") ENABLE
);



----- 공지사항 게시판

CREATE TABLE "NOTICE" (
	"NUM" NUMBER(7,0) NOT NULL ENABLE, -- 게시물 번호
	"WRITER" VARCHAR2(12) NOT NULL ENABLE, -- 작성자
	"EMAIL" VARCHAR2(30), -- 이메일
	"SUBJECT" VARCHAR2(150) NOT NULL ENABLE, -- 제목
	"PASS" VARCHAR2(10), -- 비밀번호
	"READCOUNT" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE, -- 조회수
	"REGDATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, -- 등록일
	"CONTENT" VARCHAR2(4000) NOT NULL ENABLE, -- 내용
	CONSTRAINT "NOTICE_PK" PRIMARY KEY ("NUM") ENABLE
);

CREATE SEQUENCE "NOTICE_SEQ"
START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999
NOCACHE NOCYCLE NOORDER;



----- 자유 게시판

CREATE TABLE "BOARDC" (
	"NUM" NUMBER(7,0) NOT NULL ENABLE, -- 게시물 번호
	"WRITER" VARCHAR2(12) NOT NULL ENABLE, -- 작성자
	"EMAIL" VARCHAR2(30) NOT NULL ENABLE, -- 이메일
	"SUBJECT" VARCHAR2(150) NOT NULL ENABLE, -- 제목
	"PASS" VARCHAR2(10), -- 비밀번호
	"READCOUNT" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE, -- 조회수
	"REGDATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, -- 등록일
	"CONTENT" VARCHAR2(4000) NOT NULL ENABLE, -- 내용
	CONSTRAINT "BOARDC_PK" PRIMARY KEY ("NUM") ENABLE
);

CREATE SEQUENCE "BOARDC_SEQ"
START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999
NOCACHE NOCYCLE NOORDER;



----- 자유 게시판 코멘트

CREATE TABLE "BOARDC_COMMENT" (
	"COMMENT_ID" VARCHAR2(20) NOT NULL ENABLE, --
	"NUM" NUMBER(5,0) NOT NULL ENABLE,
	"COMMENT_NAME" VARCHAR2(20),
	"COMMENTS" VARCHAR2(4000),
	"REGDATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	CONSTRAINT "BOARDC_COMMENT_PK" PRIMARY KEY ("COMMENT_ID") ENABLE
);

CREATE SEQUENCE "BOARDC_COMMENT_SEQ"
START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999
NOCACHE NOCYCLE NOORDER;



----- 질문 게시판

CREATE TABLE "QBOARD" (
	"NUM" NUMBER(7,0) NOT NULL ENABLE, -- 게시물 번호
	"WRITER" VARCHAR2(12) NOT NULL ENABLE, -- 작성자
	"EMAIL" VARCHAR2(30) NOT NULL ENABLE, -- 이메일
	"SUBJECT" VARCHAR2(150) NOT NULL ENABLE, -- 제목
	"PASS" VARCHAR2(10), -- 비밀번호
	"READCOUNT" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE, -- 조회수
	"REGDATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, -- 등록일
	"CONTENT" VARCHAR2(4000) NOT NULL ENABLE, -- 내용
	CONSTRAINT "QBOARD_PK" PRIMARY KEY ("NUM") ENABLE
);

CREATE SEQUENCE "QBOARD_SEQ"
START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999
NOCACHE NOCYCLE NOORDER;



----- 질문 게시판 코멘트

CREATE TABLE "QBOARD_COMMENT" (
	"COMMENT_ID" VARCHAR2(20) NOT NULL ENABLE,
	"NUM" NUMBER(5,0) NOT NULL ENABLE,
	"COMMENT_NAME" VARCHAR2(20),
	"COMMENTS" VARCHAR2(4000),
	"REGDATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	CONSTRAINT "QBOARD_COMMENT_PK" PRIMARY KEY ("COMMENT_ID") ENABLE
);

CREATE SEQUENCE "QBOARD_COMMENT_SEQ"
START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999
NOCACHE NOCYCLE NOORDER;



----- 공개앨범

CREATE TABLE "ALBUM" (
	"A_NUM" NUMBER(5,0) NOT NULL ENABLE, -- 게시물번호
	"A_SUBJECT" VARCHAR2(150) NOT NULL ENABLE, -- 게시물제목
	"A_WRITER" VARCHAR2(20) NOT NULL ENABLE, -- 작성자(ID)
	"A_CONTENT" VARCHAR2(4000) NOT NULL ENABLE, -- 작성내용
	"A_IMAGEPATH" VARCHAR2(100), -- 앨범이미지
	"A_LIST" VARCHAR2(500) NOT NULL ENABLE, -- 곡리스트(곡번호를 콤마[,]로 구분)
	"A_REGDATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, -- 등록일자
	"A_READCOUNT" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE, -- 조회수
	"A_RECOM" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE, -- 추천수
	CONSTRAINT "ALBUM_PK" PRIMARY KEY ("A_NUM") ENABLE
);

CREATE SEQUENCE "ALBUM_SEQ"
START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999
NOCACHE NOCYCLE NOORDER;



----- 공개앨범 COMMENT

CREATE TABLE "ALBUM_COMMENT" (
	"AC_NUM" NUMBER(5,0) NOT NULL ENABLE, -- 코멘트번호
	"AC_WRITER" VARCHAR2(20) NOT NULL ENABLE, -- 작성자(ID)
	"AC_COMMENTS" VARCHAR2(4000) NOT NULL ENABLE, -- 코멘트내용
	"AC_REGDATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, -- 등록일자
	CONSTRAINT "ALBUM_COMMENT_PK" PRIMARY KEY ("AC_NUM") ENABLE
);

CREATE SEQUENCE "ALBUM_COMMENT_SEQ"
START WITH 1 INCREMENT BY 1 MAXVALUE 99999
NOCACHE NOCYCLE NOORDER;



----- 음악리스트

CREATE TABLE "MUSICLIST" (
	"M_NUM" NUMBER(20,0) NOT NULL ENABLE, -- 곡번호
	"M_TITLE" VARCHAR2(100) NOT NULL ENABLE, -- 곡제목
	"M_SINGER" VARCHAR2(100) NOT NULL ENABLE, -- 가수
	"M_ALBUM" VARCHAR2(100) NOT NULL ENABLE, -- 곡수록앨범
	"M_CONTENT" VARCHAR2(4000) NOT NULL ENABLE, -- 참조내용
	"M_PATH" VARCHAR2(100) NOT NULL ENABLE, -- 이미지MP3경로
	"M_PCOUNT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, -- 재생횟수
	"M_DCOUNT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, -- 다운로드횟수
	"M_REGDATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, -- 등록일자
	"M_GENRE" VARCHAR2(100) DEFAULT '기타' NOT NULL ENABLE, -- 곡장르 (두개 이상인 경우 콤마[,]로 구분)
	CONSTRAINT MUSICLIST_PK PRIMARY KEY (M_NUM)
);

CREATE SEQUENCE "MUSICLIST_SEQ"
START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999
NOCACHE NOCYCLE NOORDER;



----- 앨범INFO COMMENT

CREATE TABLE "ALBUMINFORCOMMENT"(
	"AIC_COMMENTID" NUMBER(20,0) NOT NULL ENABLE, -- 댓글 id
	"AIC_ALBUMNUM" NUMBER(20,0) NOT NULL ENABLE, -- 앨범 번호
	"AIC_ID" VARCHAR2(30) NOT NULL ENABLE, -- 댓글 등록자 아이디
	"AIC_COMMENT" VARCHAR2(4000) NOT NULL ENABLE, -- 댓글 내용
	"AIC_REGDATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, -- 등록일자
	CONSTRAINT ALBUMINFORCOMMENT_PK PRIMARY KEY ("AIC_COMMENTID")
);


CREATE SEQUENCE "ALBUMINFORCOMMENT_SEQ"
START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999
NOCACHE NOCYCLE NOORDER;



----- 포인트내역

CREATE TABLE "POINT" (
	"P_ID" VARCHAR2(20) NOT NULL ENABLE, -- 회원ID
	"P_POINT" NUMBER(5,0) NOT NULL ENABLE, -- 적립 혹은 사용 포인트
	"P_USESAVE" VARCHAR2(20) NOT NULL ENABLE, -- 적립, 사용 여부 (U[사용] / S[적립])
	"P_NOTE" VARCHAR2(200) NOT NULL ENABLE, -- 포인트 적립,사용 상세내용
	"P_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE -- 적립 혹은 사용 일자
);



----- 다운로드내역

CREATE TABLE "DOWNLOAD" (
	"D_ID" VARCHAR2(20) NOT NULL ENABLE, -- 회원ID
	"D_MNUM" NUMBER(5,0) NOT NULL ENABLE, -- 곡번호
	"D_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE -- 다운로드일자
);



----- 뮤직비디오

CREATE TABLE "LINKMEDIA" (
	"LM_LINKID" NUMBER(10,0) NOT NULL, -- 미디어의 번호
	"LM_LINKNAME" VARCHAR2(100) NOT NULL, -- 미디어 콘텐츠 이름
	"LM_LINKADDRESS" VARCHAR2(1000) NOT NULL, -- 미디어 링크주소
	"LM_CONTENT" VARCHAR2(1000) NOT NULL, -- 미디어 내용
	"LM_GENRE" VARCHAR2(10) NOT NULL, -- 미디어 장르
	"LM_REGDATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, -- 미디어 등록일
	CONSTRAINT LINKMEDIA_PK PRIMARY KEY ("LM_LINKID")
);

CREATE SEQUENCE "LINKMEDIA_SEQ"
START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999
NOCACHE NOCYCLE NOORDER;